---
title: "Ch. 1 Examples"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(astsa)
plot(jj, type = 'o', ylab = 'quarterly')
plot(log(jj))

plot(globtemp, type='o', ylab='global temperature deviations')
```

```{r}
library(xts)

# approx rate of return r = log(1 + r)
djiar = diff(log(djia$Close))[-1]
plot(djiar, main = 'DJIA Returns', type = 'n')
lines(djiar)
```

```{r}
par(mfrow = c(2,1))
plot(soi, main = 'Southern Oscillation Index')
plot(rec, main = 'Recruitment')
```

```{r}
par(mfrow = c(2,1), mar = c(3,2,1,0) + .5, mgp = c(1.6,.6,0))
ts.plot(fmri1[,2:5], col=1:4, ylab='BOLD', xlab='', main='Cortex')
ts.plot(fmri1[,6:9], col=1:4, ylab='BOLD', xlab='', main='Thalam & Cereb')
mtext("Time (1 pt = 2 sec)", side=1, line=2)
```

```{r}
# Gaussian white noise
w = rnorm(500, 0, 1)

# moving average filter
v = filter(w, sides=2, rep(1/3,3))
par(mfrow=c(2,1))
plot.ts(w, main='white noise')
plot.ts(v, ylim=c(-3,3), main='moving average')
```

```{r}
# AR simulation with Gaussian white noise
w = rnorm(550, 0, 1)
x = filter(w, filter=c(1,-.9), method='recursive')[-(1:50)]
plot.ts(x, main='autoregression')
```

```{r}
set.seed(154)
w = rnorm(200)
x = cumsum(w)
wd = w + .2
xd = cumsum(wd)
plot.ts(xd, ylim=c(-5,55), main='random walk')
abline(a=0, b=.2, lty=2)
lines(x, col=4)
abline(h=0, col=4, lty=2)
```

```{r}
cs = 2*cos(2*pi*1:500/50 + .6*pi)
w = rnorm(500,0,1)
par(mfrow=c(3,1), mar=c(3,2,2,1), cex.main=1.5)
plot.ts(cs, main = expression(2*cos(2*pi*t/50 + .6*pi)))
plot.ts(cs+w, main = expression(2*cos(2*pi*t/50 + .6*pi) + N(0,1)))
plot.ts(cs+5*w, main = expression(2*cos(2*pi*t/50 + .6*pi) + N(0,5^2)))
```

```{r}
# autocorrelation with lag = 1, 6
r = round(acf(soi, 6, plot=F)$acf[-1], 3)
par(mfrow=c(1,2), mar=c(3,3,1,1), mgp=c(1.6,.6,0))
plot(lag(soi,-1), soi)
legend('topleft', legend=r[1])
plot(lag(soi,-6), soi)
legend('topleft', legend=r[6])
```

```{r}
set.seed(101011)

# autocorrelation of simulated coin tosses
x1 = 2*(2*rbinom(11, 1, .5) - 1)
x2 = 2*(2*rbinom(101, 1, .5) - 1)
y1 = 5 + filter(x1, sides=1, filter=c(1,-.5))[-1]
y2 = 5 + filter(x2, sides=1, filter=c(1,-.5))[-1]
plot.ts(y1, type='s')
plot.ts(y2, type='s')
acf(y1, lag.max=4, plot=F)
acf(y2, lag.max=4, plot=F)
```

```{r}
# autocorrelation and cross-correlation)
par(mfrow = c(3,1))
acf(soi, 48, main='Southern Oscillation Index')
acf(rec, 48, main='Recruitment')
ccf(soi, rec, 48, main='SOI vs Recruitment', ylab='CCF')
```

```{r}
set.seed(1492)

# auto and cross-correlation with prewhitened series
num = 120
t = 1:num
x = ts(2*cos(2*pi*t/12) + rnorm(num), freq=12)
y = ts(2*cos(2*pi*(t+5)/12) + rnorm(num), freq=12)
Yw = resid(lm(y ~ cos(2*pi*t/12) + sin(2*pi*t/12), na.action=NULL))
par(mfrow = c(3,2), mgp = c(1.6,.6,0), mar = c(3,3,1,1))
plot(x)
plot(y)
acf(x, 48, ylab = 'ACF(x)')
acf(y, 48, ylab = 'ACF(y)')
ccf(x, y, 24, ylab = 'CCF(x, y)')
ccf(x, Yw, 24, ylab = 'CCF(x, Yw)', ylim = c(-.6,.6))
```