---
title: "Ch. 3 Examples"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(astsa)
```

```{r}
# simulate AR(1) model
par(mfrow=c(2,1))
plot(arima.sim(list(order=c(1,0,0), ar=.9), n=100), ylab='x', main=(expression(AR(1)~~~phi==+.9)))
plot(arima.sim(list(order=c(1,0,0), ar=-.9), n=100), ylab='x', main=(expression(AR(1)~~~phi==-.9)))
```

```{r}
# simulate MA(1) model
par(mfrow=c(2,1))
plot(arima.sim(list(order=c(0,0,1), ma=.9), n=100), ylab='x', main=(expression(MA(1)~~~theta==+.9)))
plot(arima.sim(list(order=c(0,0,1), ma=-.9), n=100), ylab='x', main=(expression(MA(1)~~~theta==-.9)))
```

```{r}
# simulate AR(2) model
set.seed(8765309)
ar2 = arima.sim(list(order=c(2,0,0), ar=c(1.5,-.75)), n=144)
plot(ar2, axes=F, xlab='Time')
axis(2); axis(1, at=seq(0,144,by=12)); box()
abline(v=seq(0,144,by=12), lty=2)

# model ACF, PACF
ACF = ARMAacf(ar=c(1.5,-.75), ma=0, 24)[-1]
PACF = ARMAacf(ar=c(1.5,-.75), ma=0, 24, pacf=T)
par(mfrow=c(1,2))
plot(ACF, type='h', xlab='lag', ylim=c(-.8,1))
abline(h=0)
plot(PACF, type='h', xlab='lag', ylim=c(-.8,1))
abline(h=0)
```

```{r}
# prelim analysis (ACF, PACF) of recruitment series to determine AR or MA model
acf2(rec, 48)

# OLS estimation
regr = ar.ols(rec, order=2, demean=F, intercept=T)
names(regr)
regr$asy.se.coef # SE

# Yule-Walker estimation
rec.yw = ar.yw(rec, order=2)
names(rec.yw)
rec.yw$x.mean
sqrt(diag(rec.yw$asy.var.coef)) # SE
rec.yw$var.pred # error variance estimate
```

```{r}
# SARIMA AR(2) for recruitment series
sarima(rec,2,0,0)
sarima.for(rec, 24, 2, 0, 0)  # forecast
```

```{r}
# analysis of GNP data
plot(gnp)
acf2(gnp, 50)

gnpgr = diff(log(gnp))  # growth rate, difference-log transform
plot(gnpgr)
acf2(gnpgr)

ar1 = sarima(gnpgr,1,0,0)  # AR(1) model w/ diagnostics
ar1$AIC; ar1$AICc; ar1$BIC

ma2 = sarima(gnpgr,0,0,2)  # MA(2) model w/ diagnostics
ma2$AIC; ma2$AICc; ma2$BIC

ARMAtoMA(ar=.35, ma=0, 10)  # psi weight
```

```{r}
# analysis of mortality, temperature, pollution data
trend = time(cmort)
temp = tempr - mean(tempr) # demean temp series
temp2 = temp^2

fit = lm(cmort ~ trend + temp + temp2 + part, na.action=NULL)  # OLS to detrend, demean
acf2(resid(fit), 52)  # implies AR2, PACF drops after lag 2
sarima(cmort,2,0,0, xreg=cbind(trend, temp, temp2, part))  # residuals look like white noise, L-B stats are not significant, Q-Q plot
```

```{r}
# seasonal AR series
set.seed(666)
phi = c(rep(0,11), .9)
sAR = arima.sim(list(order=c(12,0,0), ar=phi), n=37)
sAR = ts(sAR, freq=12)

# plot simulated series
layout(matrix(c(1,2,1,3), ncol=2))
par(mar=c(3,3,2,1), mgp=c(1.6,.6,0))
plot(sAR, axes=F, main='seasonal AR(1)', xlab='year', type='c')
Months = c('J','F','M','A','M','J','J','A','S','O','N','D')
points(sAR, pch=Months, cex=1.25, font=4, col=1:4)
axis(1,1:4)
abline(v=1:4, lty=2, col=gray(.6))
axis(2)
box()

# ACF, PACF plots
ACF = ARMAacf(ar=phi, ma=0, 100)
PACF = ARMAacf(ar=phi, ma=0, 100, pacf=T)
plot(ACF, type='h', xlab='lag', ylim=c(-.1,1))
abline(h=0)
plot(PACF, type='h', xlab='lag', ylim=c(-.1,1))
abline(h=0)
```

```{r}
# mixed seasonal ARMA model
phi = c(rep(0,11), .8)
ACF = ARMAacf(ar=phi, ma=-.5, 50)[-1]
PACF = ARMAacf(ar=phi, ma=-.5, 50, pacf=T)
par(mfrow=c(1,2))
plot(ACF, type='h', xlab='lag', ylim=c(-.4,.8))
abline(h=0)
plot(PACF, type='h', xlab='lag', ylim=c(-.4,.8))
abline(h=0)

# actual series ACF, PACF
par(mfrow=c(3,1), mar=c(2,2,0,0)+1, mgp=c(1.6,.6,0))
plot(birth)  # monthly births in US
plot(diff(log(birth)))  # growth rate
acf(diff(log(birth)), 61)  # sample ACF
```

```{r}
# SARIMA model
x = AirPassengers

# diff-log transforms
lx = log(x)
dlx = diff(lx)
ddlx = diff(dlx, 12)  # diff order 12
plot.ts(cbind(x,lx,dlx,ddlx), yax.flip=T, main='')

# month plots of diff series
par(mfrow=c(2,1))
monthplot(dlx)
monthplot(ddlx)

# ARIMA(1,1,1) x (0,1,1)_12
sa1 = sarima(lx, 1,1,1, 0,1,1,12)
sa1[c('AIC','AICc','BIC')]

# ARIMA(0,1,1) x (0,1,1)_12
sa2 = sarima(lx, 0,1,1, 0,1,1,12)
sa2[c('AIC','AICc','BIC')]

# ARIMA(1,1,0) x (0,1,1)_12
sa3 = sarima(lx, 1,1,0, 0,1,1,12)
sa3[c('AIC','AICc','BIC')]
```

```{r}
# regression with lagged variables
dummy = ifelse(soi < 0, 0, 1)
fish = ts.intersect(rec, soiL6=lag(soi,-6), dL6=lag(dummy,-6), dframe=T)

# fit OLS and plot residuals, residual ACF/PACF
fit = lm(rec ~ soiL6*dL6, data=fish, na.action=NULL)
summary(fit)
attach(fish)
plot(resid(fit))
acf2(resid(fit))

# fit AR(2)
fit1 = sarima(rec,2,0,0, xreg=cbind(soiL6, dL6, I(soiL6*dL6) ))
# acf2(resid(fit1))

interact = soiL6*dL6  # interaction term

fit2 = sarima(rec,2,0,0, 1,0,0,12, xreg=cbind(soiL6, dL6, interact) )  # seasonal AR(1
fit2[c('AIC', 'AICc', 'BIC')]

fit3 = sarima(rec,2,0,0, 2,0,0,12, xreg=cbind(soiL6, dL6, interact) )  # seasonal AR(2)
fit3[c('AIC', 'AICc', 'BIC')]  # seasonal AR(2) preferred

```